   version: '3.8'

   services:
     database:
       image: postgres:16
       container_name: university_postgres
       restart: always
       ports:
         - "5432:5432"
       environment:
         POSTGRES_USER: university_user
         POSTGRES_PASSWORD: university_password
         POSTGRES_DB: university_db
       volumes:
         - db_data:/var/lib/postgresql/data

   volumes:
     db_data:
       driver: local